import { mkdir, writeFile } from 'node:fs/promises';
import * as lucideExports from '@lucide/icons';

const version = '1.50.0';
const selected = `
accessibility activity air-vent alarm-clock anchor aperture archive armchair atom award
baby backpack badge bandage banknote chart-bar battery beaker bed bell bike binoculars bird bluetooth sailboat book-open bookmark bot box briefcase brush bug building bus cake calculator calendar camera candy car caravan chart-line check hand-helping info circle-user clipboard clock cloud code-xml coffee cog compass contact cooking-pot copy cpu credit-card crown database diamond dog download droplet dumbbell earth egg eye feather file folder gamepad-2 gauge gem gift globe graduation-cap hammer hand heart house image inbox key keyboard lamp laptop leaf life-buoy lightbulb link lock mail map map-pin medal megaphone menu message-circle monitor moon mountain mouse-pointer-2 music navigation newspaper package paintbrush palette paperclip party-popper pen-tool pencil phone chart-pie pill plane plug printer puzzle qr-code radio receipt recycle rocket route ruler save scan search send server settings-2 shield shopping-bag shopping-cart smartphone snowflake sparkles speaker star store sun tablet tag target telescope tent terminal thumbs-up ticket timer tool-case train-front tree-pine trophy truck umbrella upload user users video wallet wand-sparkles watch waves-horizontal wifi wind wrench zap
`
  .trim()
  .split(/\s+/);

const byName = new Map();
for (const value of Object.values(lucideExports)) {
  if (value && typeof value === 'object' && 'name' in value && value.name) {
    byName.set(value.name, value);
  }
}

function title(name) {
  return name
    .split('-')
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join(' ');
}

function escape(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('"', '&quot;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;');
}

function attributeName(name) {
  return name.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
}

function nodeMarkup([name, attributes, children]) {
  const values = Object.entries(attributes)
    .filter(([key]) => key !== 'key')
    .map(([key, value]) => `${attributeName(key)}="${escape(value)}"`)
    .join(' ');
  return children?.length
    ? `<${name}${values ? ` ${values}` : ''}>${children.map(nodeMarkup).join('')}</${name}>`
    : `<${name}${values ? ` ${values}` : ''}/>`;
}

const records = selected.map((name) => {
  const icon = byName.get(name);
  if (!icon) throw new Error(`Missing Lucide icon: ${name}`);
  const aliases = Array.isArray(icon.aliases) ? icon.aliases : [];
  const tags = [
    ...new Set([
      ...name.split('-'),
      ...aliases.flatMap((alias) => alias.split('-')),
    ]),
  ].sort();
  return {
    catalog: 'lucide',
    catalogVersion: version,
    id: `lucide:${name}`,
    title: title(name),
    tags,
    license: 'ISC',
    sourceUrl: `https://lucide.dev/icons/${name}`,
    svg: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${icon.node.map(nodeMarkup).join('')}</svg>`,
  };
});

await mkdir(new URL('../src/data/', import.meta.url), { recursive: true });
await writeFile(
  new URL('../src/data/lucide-catalog.ts', import.meta.url),
  `// Generated by scripts/generate-catalog.js from @lucide/icons ${version}.\n` +
    `import type { CatalogIconInput } from '../catalog.js';\n\n` +
    `export const LUCIDE_CATALOG_VERSION = '${version}';\n` +
    `export const LUCIDE_CATALOG = ${JSON.stringify(records, null, 2)} as const satisfies readonly CatalogIconInput[];\n`,
);
console.log(`Generated ${records.length} curated Lucide icons.`);
